trigger:
  branches:
    include:
      - main

pool: Default

variables:
  terraformVersion: 'latest'
  azureServiceConnection: 'ApplicationSC'
  subscriptionId: 'b6571c78-f766-4999-8358-e9602abe50cf'
  tfWorkingDir: '$(System.DefaultWorkingDirectory)/environment/dev'
  backendRG: 'MyRGc'
  backendStorage: 'myst5679807578jhj'
  backendContainer: 'myrgccon'
  backendKey: 'ram.terraform.tfstate'
  approvers: '@abhi'
  notifyUsers: '@abhi'

stages:
- stage: INITSTAGE
  displayName: "Terraform Init & Plan"
  jobs:
  - job: TerraformInitPlan
    steps:

    - template: terraform-template.yaml
      parameters:
        terraformVersion: $(terraformVersion)
        tfWorkingDir: $(tfWorkingDir)
        azureServiceConnection: $(azureServiceConnection)
        subscriptionId: $(subscriptionId)
        backendRG: $(backendRG)
        backendStorage: $(backendStorage)
        backendContainer: $(backendContainer)
        backendKey: $(backendKey)
        command: init

   

    - template: terraform-template.yaml
      parameters:
        azureServiceConnection: $(azureServiceConnection)
        tfWorkingDir: $(tfWorkingDir)
        command: fmt

    - template: terraform-template.yaml
      parameters:
        tfWorkingDir: $(tfWorkingDir)
        azureServiceConnection: $(azureServiceConnection)
        subscriptionId: $(subscriptionId)
        command: plan

- stage: ValidationStage
  displayName: "Manual Approval"
  jobs:
  - job: ManualApproval
    pool: server
    steps:
    - template: manualVali-template.yaml
      parameters:
        approvers: $(approvers)
        notifyUsers: $(notifyUsers)
  
- stage: InfraDeploymentStage
  displayName: "Terraform Apply"
  dependsOn: ValidationStage
  jobs:
  - job: TerraformApply
    steps:
    - template: terraform-template.yaml
      parameters:
        terraformVersion: $(terraformVersion)
        tfWorkingDir: $(tfWorkingDir)
        azureServiceConnection: $(azureServiceConnection)
        subscriptionId: $(subscriptionId)
        backendRG: $(backendRG)
        backendStorage: $(backendStorage)
        backendContainer: $(backendContainer)
        backendKey: $(backendKey)
        command: init

    - template: terraform-template.yaml
      parameters:
        tfWorkingDir: $(tfWorkingDir)
        azureServiceConnection: $(azureServiceConnection)
        subscriptionId: $(subscriptionId)
        backendRG: $(backendRG)
        backendStorage: $(backendStorage)
        backendContainer: $(backendContainer)
        backendKey: $(backendKey)
        command: apply
        autoApprove: true
